_wandb:
    value:
        cli_version: 0.25.0
        e:
            t2x7645cuvp4sq18f4zmfeqw81gonxvb:
                args:
                    - --mode
                    - setup
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1081101176832"
                        used: "17828835328"
                email: alexrevillaperez@gmail.com
                executable: /home/alexr/project_gp_env/bin/python
                git:
                    commit: edb9c57b1c03369433be37d2a76a63a9ad158d22
                    remote: https://github.com/calico21/Project-GP.git
                gpu: NVIDIA GeForce RTX 4060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060 Laptop GPU
                      uuid: GPU-ba169738-654c-63ce-1cac-81f601baa2e5
                host: ALEXRP
                memory:
                    total: "16573976576"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /mnt/c/Users/alexr/Desktop/Ter26/Ter26 Carmaker/FS_Driver_Setup_Optimizer/main.py
                python: CPython 3.12.3
                root: /mnt/c/Users/alexr/Desktop/Ter26/Ter26 Carmaker/FS_Driver_Setup_Optimizer
                startedAt: "2026-02-22T22:41:11.379356Z"
                writerId: t2x7645cuvp4sq18f4zmfeqw81gonxvb
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 12
                - 45
            "2":
                - 12
                - 45
            "3":
                - 13
                - 16
            "4": 3.12.3
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
ensemble_size:
    value: 20
